### ISSUE TITLE
No 'version' key in the manifest file

### ISSUE THREAD

**Issue by rYdQ3J9** [robert-alfaro/genius-lyrics#11]
ERROR (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'genius_lyrics'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'genius_lyrics'

**Comment by gonzotek** [comment]
Duplicate of [issue 10](https://github.com/robert-alfaro/genius-lyrics/issues/10). [Pull request](https://github.com/robert-alfaro/genius-lyrics/pull/12) with version key in manifest.json created.

**Comment by robert-alfaro** [comment]
Fixed by #12
