### ISSUE TITLE
Genius integration stopped working 

### ISSUE THREAD

**Issue by Janne56** [robert-alfaro/genius-lyrics#13]
In the latest release of the core, core 2021.6.3, genius-lyrics integration stopped working. I had to remove the genius configuration linesfrom the configuration.yaml to restart the server.

**Comment by robert-alfaro** [comment]
Is this perhaps due to the version string missing in manifest? If so, this is fixed.  Please advise any more information @Janne56

**Comment by Janne56** [comment]
This seems to do the trick! Thank you for a prompt answer and a superb integration!!
