### ISSUE TITLE
Having trouble with the integration

### ISSUE THREAD

**Issue by TheBronxBomber** [robert-alfaro/genius-lyrics#15]
Hi,

I logged into the api with my email and I created an app and copied the access token but when I saved the configuration file it does not create a sensor like the documentation says.

I tried adding the lovelace card and it says something about the media player entity missing.

I tried refreshing the token, creating a new app and even logging in with a google account instead.

Can anyone help?

## System Health

version | core-2021.9.7
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.17-v8
arch | aarch64
timezone | America/New_York

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 3634
Installed Version | 1.18.0
Stage | running
Available Repositories | 913
Installed Repositories | 22

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.4
-- | --
update_channel | stable
supervisor_version | supervisor-2021.10.8
docker_version | 20.10.7
disk_total | 28.6 GB
disk_used | 8.4 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.3.2), Terminal & SSH (9.1.3), AirCast (3.1.1), AdGuard Home (4.2.0), eufy_security_addon (0.3.3)

</details>

<details><summary>Lovelace</summary>

dashboards | 3
-- | --
resources | 14
views | 6
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by robert-alfaro** [comment]
The README uses a hypothetical media player named `foobar`.  You'll want to replace all occurrences of `foobar` with your entity name. Is that your issue @TheBronxBomber?
