### ISSUE TITLE
Service not working

### ISSUE THREAD

**Issue by mfabiani53** [robert-alfaro/genius-lyrics#16]
The service genius_lyrics.search_lyrics is not working.
It gives me unknown error everytime i try to call it.

This is the way i try to use it:

![Schermata 2022-01-21 alle 12 35 33](https://user-images.githubusercontent.com/37701688/150520710-06a3bffd-218a-4a8a-8863-6e92980bdb84.png)

I am running HA OS 2021.12.10 on a RaspBerry pi 4

**Comment by robert-alfaro** [comment]
Thanks for reporting, I will look into this soon. I was unaware this had broken.

**Comment by mfabiani53** [comment]
I just upgraded the integration to your latest release, but this bug is still there... always "unknown error" after calling the service.

**Comment by robert-alfaro** [comment]
I'm refactoring as we speak...switching to register entity service api.

**Comment by jareau** [comment]
Not working for me either. Looks like an awesome project, though. 

![image](https://user-images.githubusercontent.com/7671154/204320746-b6c64736-0dec-4656-8072-e3958542329f.png)

**Comment by robert-alfaro** [comment]
fixing and possibly surfacing library methods as services

**Comment by robert-alfaro** [comment]
> Not working for me either. Looks like an awesome project, though.
> 
> ![image](https://user-images.githubusercontent.com/7671154/204320746-b6c64736-0dec-4656-8072-e3958542329f.png)

in your screenshot, `entity_id` should actually be the sensor entity created by the integration, like `sensor.office_mini_lyrics`
