### ISSUE TITLE
`<song title> Lyrics` included at the start of lyrics

### ISSUE THREAD

**Issue by caraar12345** [robert-alfaro/genius-lyrics#18]
Hello! Just a quick one - I've just installed `genius-lyrics` - and it's fantastic!

The one thing I've noticed though - it's prepending `<song title> Lyrics` to the start of the lyrics which looks a tad strange.

I'm not sure if it's an issue with the underlying `lyricsgenius` library but being as I've only used it here, I didn't think it fair to raise an issue there first 😄 

![Screenshot 2022-03-18 at 11 42 11](https://user-images.githubusercontent.com/6129428/158997183-ea239b4b-97de-47e5-9875-177a60516a05.png)

**Comment by antoinevandenhurk** [comment]
Great integration!
Does anyone know how to get rid of the first information line? 
[..........Verse1]

**Comment by robert-alfaro** [comment]
being addressed in new refactored branch
