### ISSUE TITLE
Lyrics sensor not reacting to kef_connector media player status

### ISSUE THREAD

**Issue by friedmannn2** [robert-alfaro/genius-lyrics#34]
I have my KEF speakers connected to HA via this integration: https://www.home-assistant.io/integrations/kef/ which provides a media player entity that works properly, and a Genius sensor was created off of that as well. However, when the media player reports a song playing, the associated genius sensor remains off and therefore does not pull any lyrics information. Anything I can do to fix this?

**Comment by robert-alfaro** [comment]
Are there any errors in the system logs? Nothing stood out in a quick glance at that integration's source, however I'll take a deeper look. If possible, could you provide screenshots of the device in Developer Settings > States? Please screenshot the portion that pertains to your media player device in various states, i.e. off, on / idle, on / playing.

**Comment by friedmannn2** [comment]
<img width="1121" alt="Screenshot 2024-08-21 at 3 18 58 PM" src="https://github.com/user-attachments/assets/a94ab2a9-f457-4e95-880c-c217ccbb3bbb">
<img width="834" alt="Screenshot 2024-08-21 at 3 18 47 PM" src="https://github.com/user-attachments/assets/de84fc58-9220-48c2-aa6c-23426105d2ac">
<img width="846" alt="Screenshot 2024-08-21 at 3 18 27 PM" src="https://github.com/user-attachments/assets/f8e571be-6306-43ca-a074-21fc04ef873e">

Here are screenshots of the device in various states, I can check for error logs if this doesn't help

**Comment by robert-alfaro** [comment]
this happens for all songs on this media player?
have you tried other media players with any success?
do you have the integration configured to monitor all or specific media players?
can you screenshot the state view for the lyrics sensor?

**Comment by friedmannn2** [comment]
Yes it happens with everything on this media player, other media players sort of work…right now I am trying it on a Sonos speaker and it is grabbing the wrong song title and incorrect lyrics (even for the title it thinks it is). i have it set to monitor all media players. here is the lyrics sensor state view while the media device is playing a song:[Screenshot 2024-08-25 at 2.47.43 PM.png][Screenshot 2024-08-25 at 2.47.35 PM.png]
Additionally here are screenshots showing the incorrect info noted above for my sonos speaker:
[Screenshot 2024-08-25 at 2.48.43 PM.png][Screenshot 2024-08-25 at 2.48.32 PM.png]
On Aug 23, 2024, at 8:12 PM, Robert Alfaro ***@***.***> wrote:



this happens for all songs on this media player?
have you tried other media players with any success?
do you have the integration configured to monitor all or specific media players?
can you screenshot the state view for the lyrics sensor?

**Comment by robert-alfaro** [comment]
@friedmannn2 sorry, it appears your email response did not allow the image to come through. Were you able to try and capture debug level logs for the integration? Based on your current screenshots, it appears the KEF media player platform does not report `media_content_type` which this integration relies on to know the media player is queued for `music`.

**Comment by robert-alfaro** [comment]
Yea.. I've confirmed by looking at their source code...no use of `ATTR_MEDIA_CONTENT_TYPE` nor `MediaType` enum. I suggest you report a bug / feature request -- however you view this issue.

Sorry I can't be of more help.
