### ISSUE TITLE
Failing to fetch lyrics

### ISSUE THREAD

**Issue by robert-alfaro** [robert-alfaro/genius-lyrics#40]
Some folks are reporting lyrics searching simply not working. States are `unknown` and `None`.

For me, I'm not getting errors like:

```
Traceback (most recent call last):
  File "/workspaces/home-assistant/homeassistant/helpers/entity.py", line 939, in async_update_ha_state
    await self.async_device_update()
  File "/workspaces/home-assistant/homeassistant/helpers/entity.py", line 1259, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/home-assistant/config/custom_components/genius_lyrics/sensor.py", line 190, in update
    self._fetch_lyrics()
  File "/workspaces/home-assistant/config/custom_components/genius_lyrics/sensor.py", line 136, in _fetch_lyrics
    song = self._genius.search_song(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/lyricsgenius/genius.py", line 402, in search_song
    search_response = self.search_all(search_term)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/lyricsgenius/api/public_methods/search.py", line 210, in search_all
    return self.search(search_term, per_page, page, endpoint)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/lyricsgenius/api/public_methods/search.py", line 45, in search
    return self._make_request(path, params_=params, public_api=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/lyricsgenius/api/base.py", line 88, in _make_request
    raise HTTPError(response.status_code, error) from e
requests.exceptions.HTTPError: [Errno 403] 403 Client Error: Forbidden for url: https://genius.com/api/search/multi?q=Count+me+in+Rebelution
```

However, on any machine behind the same public IP (including machine with HA), hitting the URL directly is successful:

`https://genius.com/api/search/multi?q=Count+me+in+Rebelution`

```
{
  "meta": {
    "status": 200
  },
  "response": {
    "sections": [
      {
        "type": "top_hit",
        "hits": [
          {
            "highlights": [],
            "index": "song",
            "type": "song",
            "result": {
              "_type": "song",
              "annotation_count": 1,
              "api_path": "/songs/1154601",
              "artist_names": "Rebelution",
              "full_title": "Count Me In by Rebelution",
              "header_image_thumbnail_url": "https://images.genius.com/d44bf17cd853d5fd785307d2ac200ec6.300x300x1.jpg",
              "header_image_url": "https://images.genius.com/d44bf17cd853d5fd785307d2ac200ec6.300x300x1.jpg",
              "id": 1154601,
              "instrumental": false,
              "lyrics_owner_id": 1549345,
              "lyrics_state": "complete",
              "lyrics_updated_at": 1466101826,
              "path": "/Rebelution-count-me-in-lyrics",
              "primary_artist_names": "Rebelution",
              "pyongs_count": null,
              "relationships_index_url": "https://genius.com/Rebelution-count-me-in-sample",
              "release_date_components": {
                "year": 2014,
                "month": 6,
                "day": 17
              },
              "release_date_for_display": "June 17, 2014",
              "release_date_with_abbreviated_month_for_display": "Jun. 17, 2014",
              "song_art_image_thumbnail_url": "https://images.genius.com/d44bf17cd853d5fd785307d2ac200ec6.300x300x1.jpg",
              "song_art_image_url": "https://images.genius.com/d44bf17cd853d5fd785307d2ac200ec6.300x300x1.jpg",
              "stats": {
                "unreviewed_annotations": 0,
                "hot": false,
                "pageviews": 14062
              },
              "title": "Count Me In",
              "title_with_featured": "Count Me In",
              "updated_by_human_at": 1481909429,
              "url": "https://genius.com/Rebelution-count-me-in-lyrics",
              "featured_artists": [],
              "primary_artist": {
...
```

Related upstream issue:  https://github.com/johnwmillr/LyricsGenius/issues/220

**Comment by antoinevandenhurk** [comment]
> Some folks are reporting lyrics searching simply not working. States are `unknown` and `None`.
> 
> For me, I'm not getting errors like:
> 
> ```
> Traceback (most recent call last):
>   File "/workspaces/home-assistant/homeassistant/helpers/entity.py", line 939, in async_update_ha_state
>     await self.async_device_update()
>   File "/workspaces/home-assistant/homeassistant/helpers/entity.py", line 1259, in async_device_update
>     await hass.async_add_executor_job(self.update)
>   File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/workspaces/home-assistant/config/custom_components/genius_lyrics/sensor.py", line 190, in update
>     self._fetch_lyrics()
>   File "/workspaces/home-assistant/config/custom_components/genius_lyrics/sensor.py", line 136, in _fetch_lyrics
>     song = self._genius.search_song(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/vscode/.local/lib/python3.11/site-packages/lyricsgenius/genius.py", line 402, in search_song
>     search_response = self.search_all(search_term)
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/vscode/.local/lib/python3.11/site-packages/lyricsgenius/api/public_methods/search.py", line 210, in search_all
>     return self.search(search_term, per_page, page, endpoint)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/vscode/.local/lib/python3.11/site-packages/lyricsgenius/api/public_methods/search.py", line 45, in search
>     return self._make_request(path, params_=params, public_api=True)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/vscode/.local/lib/python3.11/site-packages/lyricsgenius/api/base.py", line 88, in _make_request
>     raise HTTPError(response.status_code, error) from e
> requests.exceptions.HTTPError: [Errno 403] 403 Client Error: Forbidden for url: https://genius.com/api/search/multi?q=Count+me+in+Rebelution
> ```
> 
> However, on any machine behind the same public IP (including machine with HA), hitting the URL directly is successful:
> 
> `https://genius.com/api/search/multi?q=Count+me+in+Rebelution`
> 
> ```
> {
>   "meta": {
>     "status": 200
>   },
>   "response": {
>     "sections": [
>       {
>         "type": "top_hit",
>         "hits": [
>           {
>             "highlights": [],
>             "index": "song",
>             "type": "song",
>             "result": {
>               "_type": "song",
>               "annotation_count": 1,
>               "api_path": "/songs/1154601",
>               "artist_names": "Rebelution",
>               "full_title": "Count Me In by Rebelution",
>               "header_image_thumbnail_url": "https://images.genius.com/d44bf17cd853d5fd785307d2ac200ec6.300x300x1.jpg",
>               "header_image_url": "https://images.genius.com/d44bf17cd853d5fd785307d2ac200ec6.300x300x1.jpg",
>               "id": 1154601,
>               "instrumental": false,
>               "lyrics_owner_id": 1549345,
>               "lyrics_state": "complete",
>               "lyrics_updated_at": 1466101826,
>               "path": "/Rebelution-count-me-in-lyrics",
>               "primary_artist_names": "Rebelution",
>               "pyongs_count": null,
>               "relationships_index_url": "https://genius.com/Rebelution-count-me-in-sample",
>               "release_date_components": {
>                 "year": 2014,
>                 "month": 6,
>                 "day": 17
>               },
>               "release_date_for_display": "June 17, 2014",
>               "release_date_with_abbreviated_month_for_display": "Jun. 17, 2014",
>               "song_art_image_thumbnail_url": "https://images.genius.com/d44bf17cd853d5fd785307d2ac200ec6.300x300x1.jpg",
>               "song_art_image_url": "https://images.genius.com/d44bf17cd853d5fd785307d2ac200ec6.300x300x1.jpg",
>               "stats": {
>                 "unreviewed_annotations": 0,
>                 "hot": false,
>                 "pageviews": 14062
>               },
>               "title": "Count Me In",
>               "title_with_featured": "Count Me In",
>               "updated_by_human_at": 1481909429,
>               "url": "https://genius.com/Rebelution-count-me-in-lyrics",
>               "featured_artists": [],
>               "primary_artist": {
> ...
> ```
> 
> Related upstream issue: [johnwmillr/LyricsGenius#220](https://github.com/johnwmillr/LyricsGenius/issues/220)


I'm receiving this errors:
Logger: homeassistant.helpers.entity
Bron: helpers/entity.py:960
Eerst voorgekomen: 16 december 2024 om 17:17:08 (32 gebeurtenissen)
Laatst gelogd: 06:52:38

Update for sensor.genius_lyrics_mass_dell_lyrics fails
Update for sensor.genius_lyrics_pioneer_vsx_933_f37ad4_airplay_lyrics fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/lyricsgenius/api/base.py", line 80, in _make_request
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://genius.com/api/search/multi?q=I+HAD+SOME+HELP+POST+MALONE+FT.+MORGAN+WALLEN

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/usr/local/lib/python3.13/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
               ~~~~~~~~~~~~~~~^^^
  File "/usr/local/lib/python3.13/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 960, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1320, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/genius_lyrics/sensor.py", line 190, in update
    self._fetch_lyrics()
    ~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/genius_lyrics/sensor.py", line 136, in _fetch_lyrics
    song = self._genius.search_song(
        self._media_title, self._media_artist, get_full_info=False
    )
  File "/usr/local/lib/python3.13/site-packages/lyricsgenius/genius.py", line 401, in search_song
    search_response = self.search_all(search_term)
  File "/usr/local/lib/python3.13/site-packages/lyricsgenius/api/public_methods/search.py", line 210, in search_all
    return self.search(search_term, per_page, page, endpoint)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/lyricsgenius/api/public_methods/search.py", line 45, in search
    return self._make_request(path, params_=params, public_api=True)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/lyricsgenius/api/base.py", line 86, in _make_request
    error = get_description(e)
  File "/usr/local/lib/python3.13/site-packages/lyricsgenius/api/base.py", line 108, in get_description
    res = e.response.json()
  File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.genius_lyrics.sensor
Bron: custom_components/genius_lyrics/sensor.py:120
integratie: Genius Lyrics (documentatie)
Eerst voorgekomen: 16 december 2024 om 10:16:59 (227 gebeurtenissen)
Laatst gelogd: 06:52:40

Cannot fetch lyrics without artist and title

**Comment by robert-alfaro** [comment]
just tested, all good. New version releasing soon!

**Comment by antoinevandenhurk** [comment]
That's good news, can't wait for the new release

**Comment by cellard0or** [comment]
Release is out and now it is working, nice job!

**Comment by Sidsapphire** [comment]
can you share the config i never got it working with instructions given here

**Comment by robert-alfaro** [comment]
Hi @Sidsapphire, can you elaborate on which config? If you're looking to setup this integration, you install via hacs, then add integration using the UI in home assistant. No configuration.yaml.

Are you referring to a lovelace markdown card?

**Comment by Thom-Pryde** [comment]
> Release is out and now it is working, nice job!

Hey, I am getting the same 403 forbidden error as people before even when using the agent header. Is the only way around this through a proxy?

**Comment by simonwichmann-tomtom** [comment]
I see "Lyrics not found" now, but nothing in the log. No changes on my side.

**Comment by robert-alfaro** [comment]
"works on my machine" .. can you share more information @Thom-Pryde -- logs, versions, etc.?

**Comment by Thom-Pryde** [comment]
> "works on my machine" .. can you share more information [@Thom-Pryde](https://github.com/Thom-Pryde) -- logs, versions, etc.?

![Image](https://github.com/user-attachments/assets/a340542a-e44f-4f8d-9b2c-6291d12fdc27)

**Comment by Thom-Pryde** [comment]
> "works on my machine" .. can you share more information [@Thom-Pryde](https://github.com/Thom-Pryde) -- logs, versions, etc.?

![Image](https://github.com/user-attachments/assets/b6294057-0ac8-44d7-a524-9d6857633e28)

The URL [https://genius.com/api/search/multi?q=My+All+Mariah+Carey](url) seems to work but still getting the error. 
Works locally but not on deployment. 

Running lyricsgenius==3.2.0

![Image](https://github.com/user-attachments/assets/f2f8c60b-7ed9-4a46-bb8a-665f6d8b0c3b)

**Comment by FelipeValencio** [comment]
Was facing same problem, a clean install solved for me
